-- This query adds a little bit of financial feature to the database: it computes the total income generated by a doctor and also computes the bonus that he recieves ( 5% of the income generated ).
-- Also, the bonus is added to the base salary.

-- output: Name, totalIncomeGenerated, Bonus = ( totalIncomeGenerated * 0.05 ), BaseSalary, FinalSalary = ( BaseSalary + Bonus )

-- SELECT #4: We get the doctor name, the total income that he generated ( sum of all incomes generated by the medicine he prescribed ) and the bonus that he recieves from the sales ( which is 5% ).
--            We also get the base salary for each doctor and compute the final salary.
SELECT TABLE3.name AS Name, TABLE3.TotalIncomeGenerated,  TABLE3.totalIncomeGenerated*0.05 AS Bonus, Doctors.salary as BaseSalary, Doctors.salary+TABLE3.totalIncomeGenerated*0.05 AS FinalSalary
FROM (
		-- SELECT #3: We get the doctor name, the total income that he generated ( sum of all incomes generated by the medicine he prescribed ).
		SELECT TABLE2.name, SUM(TABLE2.incomeGenerated) AS TotalIncomeGenerated
		FROM (  
				-- SELECT #2 : We get the doctor name and the income generated by each medicine he prescribed ( which is equal with: the quantity of the medicine * the price/medicine )
				SELECT Doctors.name, TABLE1.cost * TABLE1.quantity AS incomeGenerated
				FROM (  
						-- SELECT #1 : We get a table with every medicine id which was prescribed, its name, its cost, the prescribed quantity, description ( if it was bought or not ) and the doctor who prescribed it.
						SELECT Medications.mid, Medications.name, Medications.cost,  Prescribed_Medications.quantity, Prescribed_Medications.description, Prescribed_Medications.did
						FROM Medications
						INNER JOIN Prescribed_Medications
						ON Medications.mid = Prescribed_Medications.mid
						FULL JOIN Prescriptions
						ON Prescriptions.pid = Prescribed_Medications.pid
						-- We are only interested in the medicine which was bought by the customer ( the medicine be: bought, ordered and not bought ).
						WHERE Prescribed_Medications.description = 'Cumparat'
					 ) TABLE1

				LEFT JOIN Doctors
				ON TABLE1.did = Doctors.did
			 ) TABLE2

		GROUP BY TABLE2.name
	 ) AS TABLE3

LEFT JOIN Doctors
ON Table3.name = Doctors.name